#pragma once

#include <sofa/component/linearsolver/config.h>

#ifdef SOFA_BUILD_SOFAGENERALLINEARSOLVER
#  define SOFA_SOFAGENERALLINEARSOLVER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAGENERALLINEARSOLVER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
