#pragma once

#include <sofa/component/linearsolver/config.h>

#ifdef SOFA_BUILD_SOFABASELINEARSOLVER
#  define SOFA_SOFABASELINEARSOLVER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFABASELINEARSOLVER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#define SOFABASELINEARSOLVER_ENABLE_CRSMULTIMATRIXACCESSOR 0
#ifdef SOFA_BUILD_SOFABASELINEARSOLVER
#define SOFA_ATTRIBUTE_DISABLED__CGLINEARSOLVER_DATANAME(msg)
#else
#define SOFA_ATTRIBUTE_DISABLED__CGLINEARSOLVER_DATANAME(msg) \
    SOFA_ATTRIBUTE_DISABLED( \
        "v21.06 (PR#2098)", "v21.12", msg)
#endif
