#pragma once

#include <sofa/components/odesolver/config.h>

#ifdef SOFA_BUILD_SOFAGENERALIMPLICITODESOLVER
#  define SOFA_SOFAGENERALIMPLICITODESOLVER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAGENERALIMPLICITODESOLVER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
