#pragma once

#include <sofa/component/visual/gl/config.h>

#ifdef SOFA_BUILD_SOFAOPENGLVISUAL
#  define SOFA_SOFAOPENGLVISUAL_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAOPENGLVISUAL_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
