#pragma once

#include <sofa/component/animationloop/config.h>

#ifdef SOFA_BUILD_SOFAGENERALANIMATIONLOOP
#  define SOFA_SOFAGENERALANIMATIONLOOP_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAGENERALANIMATIONLOOP_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
