#pragma once

#include <sofa/component/constraint/projective/config.h>

#ifdef SOFA_BUILD_SOFABOUNDARYCONDITION
#  define SOFA_SOFABOUNDARYCONDITION_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFABOUNDARYCONDITION_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#ifdef SOFA_BUILD_SOFABOUNDARYCONDITION
#define SOFA_ATTRIBUTE_DEPRECATED__POINTCONSTRAINT()
#else
#define SOFA_ATTRIBUTE_DEPRECATED__POINTCONSTRAINT() \
    SOFA_ATTRIBUTE_DISABLED( \
        "v21.12", "v22.06", \
        "As an alternative, use FixedConstraint.")
#endif
