#pragma once

#include <sofa/component/animationloop/config.h>

#ifdef SOFA_BUILD_SOFA_COMPONENTS_ANIMATIONLOOP
#  define SOFA_SOFACONSTRAINT_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFACONSTRAINT_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif