#pragma once

#include <sofa/components/VISUAL/config.h>

#ifdef SOFA_BUILD_SOFAGENERALVISUAL
#  define SOFA_SOFAGENERALVISUAL_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAGENERALVISUAL_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
