#pragma once

#include <sofa/components/linearsolver/config.h>

#define SOFASPARSESOLVER_HAVE_METIS SOFA_COMPONENTS_LINEARSOLVER_HAVE_METIS
#define SOFASPARSESOLVER_HAVE_CSPARSE SOFA_COMPONENTS_LINEARSOLVER_HAVE_CSPARSE 1

#ifdef SOFA_BUILD_SOFASPARSESOLVER
#  define SOFA_SOFASPARSESOLVER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFASPARSESOLVER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
