#pragma once

#include <sofa/components/constraint/projective/config.h>

#ifdef SOFA_BUILD_SOFAGENERALOBJECTINTERACTION
#  define SOFA_SOFAGENERALOBJECTINTERACTION_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAGENERALOBJECTINTERACTION_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif
